car/urls.py
from . import views
from django.urls import path
app_name = 'car'

urlpatterns = [
    path('review',view= views.review,name='Review'),
    path('thanks',view= views.thanks,name='Thanks'),

]

first_app/urls.py
from django.urls import path
from . import views
# from .views import ClassBased

app_name = 'first_app'
urlpatterns = [
    # # path('index',view= views.index), #static routing
    # path('<str:nth>/',view= views.index , name= 'first'), # dynamic routing
    # path('<int:n>',view= views.red), #redirect
    # path('<int:x>/<int:y>',view= views.add_result) # dynamic(more param) routing
    path('',views.example_view,name='example'), #domain.com/first_app
    # path('variable',views.var_view,name='variable'),
    path('test',views.test,name='test'),
    path('img_test',views.img_test,name='img_test'),
    path('class',views.ClassBased.as_view(),name='class_based')


     #domain.com/first_app

]

mysite/urls.py
from cgitb import handler
from django.contrib import admin
from django.http import HttpResponse
from django.urls import path,include
from . import views

# def home_view(request):
    # return HttpResponse('This is Home Page')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',view= views.home_view,name='Homepage'), #Homepage
    path('first_app/',include('first_app.urls')),
    path('office/',include('office.urls')),
    path('car/',include('car.urls')),

]

office/urls.py
from django.urls import path
from . import views

app_name = 'office'
urlpatterns = [
    path('',views.list_patients,name='list_patients'),
 
]

car/models.py
from operator import mod
from django.db import models
from django.core.validators import MaxValueValidator,MinValueValidator

# Create your models here.
class Review(models.Model):
    first_name = models.CharField(max_length= 100)
    last_name = models.CharField(max_length= 100)
    stars = models.IntegerField(validators=[MinValueValidator(1),MaxValueValidator(5)])

office/models.py
from django.db import models
from django.core.validators import MaxValueValidator,MinValueValidator
# Create your models here.
class Patient(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    age = models.IntegerField(validators=[MinValueValidator(0),MaxValueValidator(120)])
    heartrate = models.IntegerField(default=60,validators=[MinValueValidator(1),MaxValueValidator(300)])

    def __str__(self):
        return f"{self.first_name} {self.last_name} is {self.age} years old and the heartrate is {self.heartrate}"

car/forms.py
from cProfile import label
from distutils.log import error
from tkinter.tix import Form
from xml.parsers.expat import model
from django import forms
from pyrsistent import field
from .models import Review
from django.forms import ModelForm


# class Review_form(forms.Form):
#     first_name = forms.CharField(label = 'first-name', max_length= 100)
#     last_name = forms.CharField(label = 'last-name', max_length= 100)
#     email = forms.CharField(label = 'Email')
#     review = forms.CharField(label = 'Write your Review',
#                                                 widget = forms.Textarea(attrs={'class':'my_form'}))
    
class Review_form(ModelForm):
    class Meta:
        model = Review
        fields = ['first_name','stars']        
        labels = {'first_name' : "your firstname"}
        error_messages = { 
            'stars' : {'min_value':'min error',
                        'max_value':'max error'}
        }
        # fields = '__all__'

car/views.py
import django
from django.shortcuts import render,redirect
from django.urls import reverse
from .forms import Review_form
# Create your views here.
def review(request):
    if request.method == 'POST':
        form = Review_form(request.POST)
        if form.is_valid():
            print(form.cleaned_data)
            form.save()
            return redirect(reverse('car:Thanks'))
    else:
        form = Review_form()
    
    return render(request,'car/review.html',context = {'form':form})

def thanks(request):
    return render(request,'car/thanks.html')

first_app/views.py
import django
from django.urls import reverse
from pydoc_data.topics import topics
from django.shortcuts import render
from django.http import Http404, HttpResponse, HttpResponseNotFound, HttpResponseRedirect
from django.views.generic import TemplateView
# Create your views here.

# my_views = {
#     'first' : 'first page',
#     'second' : 'second page',
#     'last' : 'last page'
# }

# def index(request,nth):
#     try:
#         return HttpResponse(my_views[nth])
#     except:
#         raise(Http404('Not found'))
#         # return HttpResponseNotFound()

# def add_result(request,x,y):
#     result = f"{x} + {y} = {x+y}" 
#     return HttpResponse(result)


# def red(request,n):
#     my_views_list = list(my_views.keys())
#     nth = my_views_list[n]
#     print(nth)
#     return HttpResponseRedirect(reverse('first',args= [nth]))

def example_view(request):
    # var = {'user_logged_in' : True , 'num_list' : [1,2,3,4]}
    return render(request,'first_app/example.html')

# def var_view(request):
#     # var = {'user_logged_in' : True , 'num_list' : [1,2,3,4]}
#     return render(request,'first_app/variable.html')

def test(request):
    # var = {'user_logged_in' : True , 'num_list' : [1,2,3,4]}
    return render(request,'first_app/test.html')

def img_test(request):
    return render(request,'first_app/static_test.html')

class ClassBased(TemplateView):
    template_name = 'first_app/class_based.html'

mysite/views.py
from os import rename
from django import http
from django.http import HttpResponse
from django.shortcuts import render

def home_view(request):
    return render(request,'homepage.html')

office/views.py
# Create your views here.
from django.urls import reverse
from pydoc_data.topics import topics
from django.shortcuts import render
from django.http import Http404, HttpResponse, HttpResponseNotFound, HttpResponseRedirect
from matplotlib.style import context
from . import models
# Create your views here.
def list_patients(request):
    # var = {'user_logged_in' : True , 'num_list' : [1,2,3,4]}
    all_patients = models.Patient.objects.all()
    context_list = {'Patients':all_patients}
    return render(request,'office/index.html',context= context_list)

templates/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {% comment %} <link rel="stylesheet" href= "{% static '/first_app/style1.css' %}"> {% endcomment %}

</head>
    <body>
        <h1>
            header!
        </h1>
    {% block content %}

    {% endblock content %}
    <h2>
        <a href = "{%url 'Homepage'%}">
        back
    </h2>
    </body>
</html>

templates/car/review.html
{% extends 'base.html' %}
{%block content%}
{% load static%}
<link rel ="stylesheet" href = "{% static 'car/css/style.css' %}">
<h1>
review
</h1>
<p> hello</p>
<form method = "POST" >
    {% csrf_token %}
    {% comment %} {{form.as_p}} {% endcomment %}
    {%for field in form%}
    <div>
        {{field.label_tag}}{{field}}{{field.errors}}
    </div>
    {% endfor %}
    <input type = "submit">
</form>
{%endblock%}

templates/car/thanks.html
{% extends 'base.html' %}
{%block content%}
<h1>
    thank you
</h1>
{%endblock%}

templates/first_app/class_based.html
{% extends 'base.html' %}
{%block content%}
<h1>
class based working
</h1>
{%endblock%}

templates/first_app/example.html
{% extends 'base.html' %} 

{% block content %}

<h1>
    inside block -Exapmle-

</h1>

{% endblock content %}

templates/first_app/static_test.html
{% load static %}

<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel ="stylesheet" href = "{% static 'first_app/css/style.css' %}">

        <title>Document</title>
    </head>
    <body>
        <h1>
            img test!
        </h1>
        <img src="{% static "first_app/img/django.jpg" %}" alt="My image">
        <h2>
            <a href = "{%url 'Homepage'%}">
            back
        </h2>
</body>
</html>

templates/first_app/test.html
{% extends 'base.html' %} 
    <h1>
        test!
    </h1>
{% block content %}
    <h2> 
        inside block -test-
    </h2>
{% endblock %}

templates/homepage.html
{%load static%}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel ="stylesheet" href = "{% static 'style.css' %}">
        {% comment %} <link rel="stylesheet" href="{% static "first_app/style.css" %}" > {% endcomment %}

        <title>Document</title>
    </head>
    <body>
        <h1>
            homepage
        </h1>
        <h2>
            <a href = "{%url 'first_app:example'%}">
                Exapmle
        </h2>
        <h2>
            <a href = "{%url 'first_app:test'%}">
                Test
        </h2>
        <h2>
            <a href = "{%url 'first_app:img_test'%}">
            Test IMG
        </h2>
        <h2>
            <a href = "{%url 'office:list_patients'%}">
            Test DB
        </h2>
        <h2>
            <a href = "{%url 'car:Review'%}">
            Review
        </h2>        
        <h2>
            <a href = "{%url 'first_app:class_based'%}">
            check class based
        </h2> 
    </body>
    </html>

templates/office/index.html
{% extends 'base.html' %} 

    {% block content %}
    
    <h1>
        {{Patients}}
        <ul>
        {%for p in Patients%}
        <li>{{p.first_name}}</li>
        {% endfor %}
        </ul>
    </h1>
    
    {% endblock content %}